IMAGE_REGEXP = r"\.(jpeg|png|jpg|svg)$"
VIDEO_REGEXP = r"\.(avi|mp4|mov|mkv)$"
DOCUMENT_REGEXP = r"\.(doc|docx|txt|pdf|xlsx|pptx)$"
AUDIO_REGEXP = r"\.(mp3|ogg|wav|amr)$"
ARCHIVE_REGEXP = r"\.(zip|gz|tar)$"
