"""added user_id to contact

Revision ID: b7d617a8ab27
Revises: 732c42e2696b
Create Date: 2024-04-24 21:31:15.461271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b7d617a8ab27"
down_revision: Union[str, None] = "732c42e2696b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("contacts", sa.Column("user_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        None, "contacts", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "contacts", type_="foreignkey")
    op.drop_column("contacts", "user_id")
    # ### end Alembic commands ###
