"""added deleted_at

Revision ID: d314883633a6
Revises: c0044a7f2928
Create Date: 2024-03-23 17:43:42.439688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d314883633a6"
down_revision: Union[str, None] = "c0044a7f2928"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("contacts", sa.Column("deleted_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("contacts", "deleted_at")
    # ### end Alembic commands ###
