"""remove table note_tag

Revision ID: 267c543261e7
Revises: 6e07d212681b
Create Date: 2024-02-17 16:20:19.734314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "267c543261e7"
down_revision: Union[str, None] = "6e07d212681b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("note_tag")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "note_tag",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("note_id", sa.INTEGER(), nullable=True),
        sa.Column("tag_id", sa.INTEGER(), nullable=True),
        sa.ForeignKeyConstraint(["note_id"], ["notes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tag_id"], ["notes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###
