version: '3.1'

services:

  db:
    image: postgres:16.1
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: hw-11
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - type: bind
        source: ./db
        target: /var/lib/postgresql/data
